### PR TITLE
typo in cookie name

### PR DESCRIPTION
**Pull request by jnorell**
fix typo

### CODE REVIEW

**Comment by Reedyseth** [comment]
Hi @jnorell more than a typo I see that you added an underscore. Is this causing issues to you ?

**Comment by jnorell** [comment]
Hello  @Reedyseth,

That particular typo is not causing me an issue, no, but I believe the correct cookie name includes the underscore, as used elsewhere in that file, in wp-includes/comment.php, etc.

Thanks!

**Comment by Reedyseth** [comment]
I see, thank you for that, I will check adding that undercore and test it, cause I don't want to override the WP cookies, maybe changing the StCR cookie name.

**Comment by jnorell** [comment]
My understanding from looking at the code is that the plugin is trying to emulate what wordpress does when you add a comment, ie. wordpress will set the cookie "'comment_author_email_' . COOKIEHASH" when adding a comment, and the stcr plugin checks/uses that cookie at other places, so that same cookie name is what should be set in setUserCoookie() when a users subscribes without commenting, to store the email address in the same manner as if the user had actually cpmmented.

**Comment by Reedyseth** [comment]
Haha, yes, Actually I was think about that this morning, So I will go ahead with the merge. Thank you !!

**Pull request merged**
