### PR TITLE
Mail messages localization support for WPML

### PR DESCRIPTION
**Pull request by IvanRF**
Added support for WPML in notification messages

### CODE REVIEW

**Comment by IvanRF** [comment]
Look here: [Commits pre_release](https://github.com/IvanRF/subscribe-to-comments-reloaded/commits/pre_release)
I made commits over that latest commit ec65388.

**Comment by Reedyseth** [comment]
OK everything looks good, just one last test that I will run and we are ready to merge.

**Comment by Reedyseth** [comment]
Since I don't have WPML installed and I don't want to pay for it( for the moment I don't need it ) I have no way to debug and test your code. Can you share you tests  here with screenshots? or something that prove that the code is fully functional?

**Comment by IvanRF** [comment]
OK, give me a moment. I'll send you debug screens

**Comment by IvanRF** [comment]
Here are debug images for English and Spanish.

en-01
en-02
es-01
es-02

**Comment by Reedyseth** [comment]
Great, thank you for your effort.

**Pull request merged**
