### PR TITLE
sanitizing and encoding, fixes #431 (xss)

### LINKED ISSUE #431: Cross-site scripting vulnerability: MANAGE SUBSCRIPTIONS
Recently we had security audit on one our websites and this plugin showed a cross-site scripting vulnerability. From what I could tell this is happening on the MANAGE SUBSCRIPTIONS/comment-subscriptions page when JS is turned off and in the email input field. I was able to submit script tags and js.

### PR DESCRIPTION
**Pull request by jnorell**

### CODE REVIEW

**Comment by Reedyseth** [comment]
Hello @jnorell ,
I am working to merge this code on the development version, but I will change some functions for WordPress function built in to sanitize information. For example `wp_json_encode( $email )` is no sanitizing the information. You can review the function to get more details. I will accept you changes and the replace the functions.

Best regards and thank you for your contributions.

**Comment by Reedyseth** [comment]
@jnorell Thank you for your contribution. I have added you code to the latest dev code https://github.com/stcr/subscribe-to-comments-reloaded/commit/2f37d33dc78be48433e4477e097d6103cfb635fc. I am working this day to get the new version for the next week. You are happy to download the dev version and testing.

**Comment by jnorell** [comment]
Thanks for picking this up, @Reedyseth!

 Regarding that wp_json_encode( $email ), I believe it should not be a problem because all paths to set $email are safe, it either comes from the global $current_user object or from a cookie where it is run through sanitize_email().  I did attempt to trace all code paths to set the variables to ensure they were safe (though as always you can miss something, so I just double-checked and came to the same conclusion).  So it appears $email is sanitized before handing to wp_json_encode(), which will then encode whatever value it is given (a sanitized email address or anything else) and encode it safely for javascript output.

I'll take a look at the latest code and get things updated - thanks again!

**Comment by Reedyseth** [comment]
@jnorell The function `wp_json_encode()` does not convice me about sanitizing information. As you can see on the video I have debug the code and in no point the information is sanitize as in `esc_attr()`

[out-12.ogv.tar.gz](https://github.com/stcr/subscribe-to-comments-reloaded/files/2678819/out-12.ogv.tar.gz)

Please share your comments. I just want to be clear about using the correct functions.

Regards.!!

**Pull request closed without merging**
