### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by IvanRF**
100% translation, and some fixes.

### CODE REVIEW

**Comment by IvanRF** [comment]
I saw you updated German translations, can you update Spanish too, thanks!

**Comment by Reedyseth** [comment]
Yes @IvanRF , sorry for the late response

**Comment by IvanRF** [comment]
The other day I noticed that in this plugin there a translation for "Settings" which overrides the original WordPress translation. I removed that entry from WPML that solved it.

Just to know, should a plugin override a translation from WordPress core? I guess it's ok, since if WordPress remove the translation in the future, the plugin will not have it. Am I right?

**Comment by Reedyseth** [comment]
As mention on #135 the translation reference was updated so please check them and submit another pull request.

**Comment by Reedyseth** [comment]
> Just to know, should a plugin override a translation from WordPress core? I

This translation is inherited from the old code. I think that the plugin should not override the WP Core translation. So if WP is in Spanish the Settings word will translated by WordPress and StCR will be also in Spanish so there is no need to do this. Please add this into a new ticket so that I can track it down.The reference is here https://github.com/stcr/subscribe-to-comments-reloaded/blob/pre_release/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php#L116

**Pull request merged**
