### PR TITLE
Minor string bugs

### PR DESCRIPTION
**Pull request by IvanRF**
https://github.com/stcr/subscribe-to-comments-reloaded/issues/124

### CODE REVIEW

**Comment by Reedyseth** [comment]
@IvanRF On this changes I have decided to leave the strings like this because it fits the IDE better without having to scroll to the right.

**Comment by IvanRF** [comment]
That's fine, but then you need to split the string with a ' . '

**Comment by IvanRF** [comment]
(to avoid the \t\t\t\t\t\t\t\t\t\t\t\t\t in the translation strings)

**Comment by Reedyseth** [comment]
> (to avoid the \t\t\t\t\t\t\t\t\t\t\t\t\t in the translation strings)

Got it, will merge. !

**Comment by Reedyseth** [comment]
Merged ! Thank you for your contribution.

**Comment by IvanRF** [comment]
When you update the .po, I'll update the Spanish translation. Thanks!

**Comment by Reedyseth** [comment]
It is updated already see https://github.com/stcr/subscribe-to-comments-reloaded/blob/pre_release/subscribe-to-comments-reloaded/langs/subscribe-reloaded-es_ES.po#L6

just pull the changes.

**Comment by IvanRF** [comment]
I meant with these last changes, the \t\t\t are still there

**Pull request merged**
